DROP TABLE IF EXISTS {mimic_derived}.pivoted_bg_art;

CREATE TABLE {mimic_derived}.pivoted_bg_art (
  hadm_id integer,
  icustay_id integer,
  charttime timestamp without time zone,
  specimen text,
  specimen_pred text,
  specimen_prob double precision,
  so2 double precision,
  spo2 double precision,
  po2 double precision,
  pco2 double precision,
  fio2_chartevents double precision,
  fio2 double precision,
  aado2 double precision,
  aado2_calc double precision,
  pao2fio2ratio double precision,
  ph double precision,
  baseexcess double precision,
  bicarbonate double precision,
  totalco2 double precision,
  hematocrit double precision,
  hemoglobin double precision,
  carboxyhemoglobin double precision,
  methemoglobin double precision,
  chloride double precision,
  calcium double precision,
  temperature double precision,
  potassium double precision,
  sodium double precision,
  lactate double precision,
  glucose double precision,
  intubated double precision,
  tidalvolume double precision,
  ventilationrate double precision,
  ventilator double precision,
  peep double precision,
  o2flow double precision,
  requiredo2 double precision
);
