DROP TABLE IF EXISTS {mimic_derived}.pivoted_bg;

CREATE TABLE {mimic_derived}.pivoted_bg (
  icustay_id integer,
  hadm_id integer,
  charttime timestamp without time zone,
  specimen text,
  aado2 double precision,
  baseexcess double precision,
  bicarbonate double precision,
  totalco2 double precision,
  carboxyhemoglobin double precision,
  chloride double precision,
  calcium double precision,
  glucose double precision,
  hematocrit double precision,
  hemoglobin double precision,
  intubated double precision,
  lactate double precision,
  methemoglobin double precision,
  o2flow double precision,
  fio2 double precision,
  so2 double precision,
  pco2 double precision,
  peep double precision,
  ph double precision,
  po2 double precision,
  potassium double precision,
  requiredo2 double precision,
  sodium double precision,
  temperature double precision,
  tidalvolume double precision,
  ventilationrate double precision,
  ventilator double precision
);
